CREATE TABLE IF NOT EXISTS `char_premium_buff` (
 `obj_Id` INT NOT NULL DEFAULT 0,
 `account` VARCHAR(45) NOT NULL DEFAULT '',
 `ip` VARCHAR(15) NOT NULL DEFAULT '',
 `hwid` VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY  (`obj_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;