CREATE TABLE IF NOT EXISTS `character_donate` (
	`id` INT(9) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	`obj_Id` INT(11) NOT NULL DEFAULT 0,
	`char_name` VARCHAR(35) CHARACTER SET UTF8 NOT NULL DEFAULT '',
	`item_id` INT(9) NOT NULL DEFAULT 0,
	`count` INT(11) NOT NULL DEFAULT 1,
	`enchant` INT(5) NOT NULL DEFAULT 0,
	`given` TINYINT NOT NULL DEFAULT 0);