CREATE TABLE IF NOT EXISTS characters (
  `account_name` VARCHAR(45) NOT NULL DEFAULT '',
  `obj_Id` INT NOT NULL DEFAULT 0,
  `char_name` VARCHAR(35) CHARACTER SET UTF8 NOT NULL DEFAULT '',
  `face` TINYINT UNSIGNED DEFAULT NULL,
  `hairStyle` TINYINT UNSIGNED DEFAULT NULL,
  `hairColor` TINYINT UNSIGNED DEFAULT NULL,
  `sex` BOOLEAN DEFAULT NULL,
  `heading` mediumint DEFAULT NULL,
  `x` mediumint DEFAULT NULL,
  `y` mediumint DEFAULT NULL,
  `z` mediumint DEFAULT NULL,
  `karma` INT DEFAULT NULL,
  `pvpkills` INT DEFAULT NULL,
  `pkkills` INT DEFAULT NULL,
  `clanid` INT DEFAULT NULL,
  `createtime` INT UNSIGNED NOT NULL DEFAULT 0,
  `deletetime` INT UNSIGNED NOT NULL DEFAULT 0,
  `title` VARCHAR(16) CHARACTER SET UTF8 DEFAULT NULL,
  `rec_have` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `rec_left` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `accesslevel` TINYINT DEFAULT NULL,
  `online` BOOLEAN DEFAULT NULL,
  `onlinetime` INT UNSIGNED NOT NULL DEFAULT 0,
  `lastAccess` INT UNSIGNED NOT NULL DEFAULT 0,
  `leaveclan`  INT UNSIGNED NOT NULL DEFAULT 0,
  `deleteclan` INT UNSIGNED NOT NULL DEFAULT 0,
  `nochannel` INT NOT NULL DEFAULT 0, -- not UNSIGNED, negative value means 'forever'
  `noble` decimal(2,0) NOT NULL DEFAULT 0,
  `ketra` decimal(5,0) NOT NULL DEFAULT 0,
  `varka` decimal(5,0) NOT NULL DEFAULT 0,
  `ram` decimal(5,0) NOT NULL DEFAULT 0,
  `pledge_type` SMALLINT NOT NULL DEFAULT 0,
  `pledge_rank` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `lvl_joined_academy` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `apprentice` INT UNSIGNED NOT NULL DEFAULT 0,
  `key_bindings` varbinary(8192) default NULL,
  `pcBangPoints` INT NOT NULL DEFAULT 0,
  `LastHWID` VARCHAR(64) DEFAULT '',
  `lastteleport` decimal(20,0) DEFAULT NULL,
  PRIMARY KEY (obj_Id),
  UNIQUE KEY `char_name` (`char_name`),
  KEY `account_name` (`account_name`),
  KEY `clanid` (`clanid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;