CREATE TABLE IF NOT EXISTS `hwid_locks` (
 `obj_Id` INT NOT NULL DEFAULT 0,
 `Lock1` VARCHAR(64) DEFAULT '',
 `Lock2` VARCHAR(64) DEFAULT '',
  PRIMARY KEY (obj_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
