CREATE TABLE IF NOT EXISTS `hwid_bans` (
 `player` VARCHAR(35) CHARACTER SET UTF8 NOT NULL DEFAULT '',
 `HWID` VARCHAR(64) DEFAULT '',
 `reason` VARCHAR(300) CHARACTER SET UTF8 NOT NULL DEFAULT '',
 `GM` VARCHAR(35) CHARACTER SET UTF8 NOT NULL DEFAULT '',
 `end_date` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY  (`HWID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;